on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please-release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
        with:
          skip-github-pull-request: true
          repo-url: mdn/rari
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}
